
export const catBreedsOptions: any[] = [
  { value: 'mixed', label: 'Mestizo / Criollo / Sin raza definida' },
  { value: 'abyssinian', label: 'Abisinio' },
  { value: 'aegean', label: 'Egeo' },
  { value: 'american_bobtail', label: 'Bobtail Americano' },
  { value: 'american_curl', label: 'American Curl' },
  { value: 'american_shorthair', label: 'American Shorthair' },
  { value: 'american_wirehair', label: 'American Wirehair' },
  { value: 'aphrodite_giant', label: 'Afrodita Gigante' },
  { value: 'arabian_mau', label: 'Mau Árabe' },
  { value: 'asian', label: 'Asiático' },
  { value: 'asian_semi-longhair', label: 'Asiático de Pelo Semilargo' },
  { value: 'australian_mist', label: 'Mist Australiano' },
  { value: 'balinese', label: 'Balines' },
  { value: 'bambino', label: 'Bambino' },
  { value: 'bengal', label: 'Bengalí' },
  { value: 'birman', label: 'Birmano' },
  { value: 'bombay', label: 'Bombay' },
  { value: 'brazilian_shorthair', label: 'Pelo Corto Brasileño' },
  { value: 'british_longhair', label: 'British Longhair' },
  { value: 'british_shorthair', label: 'British Shorthair' },
  { value: 'burmese', label: 'Burmés' },
  { value: 'burmilla', label: 'Burmilla' },
  { value: 'california_spangled', label: 'California Spangled' },
  { value: 'chantilly-tiffany', label: 'Chantilly-Tiffany' },
  { value: 'chartreux', label: 'Chartreux' },
  { value: 'chausie', label: 'Chausie' },
  { value: 'colorpoint_shorthair', label: 'Colorpoint de Pelo Corto' },
  { value: 'cornish_rex', label: 'Cornish Rex' },
  { value: 'cymric', label: 'Cymric' },
  { value: 'cyprus', label: 'Chipriota' },
  { value: 'devon_rex', label: 'Devon Rex' },
  { value: 'donskoy', label: 'Donskoy' },
  { value: 'dragon_li', label: 'Dragon Li' },
  { value: 'dwarf_cat', label: 'Gato Enano' },
  { value: 'egyptian_mau', label: 'Mau Egipcio' },
  { value: 'european_shorthair', label: 'Europeo de Pelo Corto' },
  { value: 'exotic_shorthair', label: 'Exótico de Pelo Corto' },
  { value: 'foldex', label: 'Foldex' },
  { value: 'german_rex', label: 'German Rex' },
  { value: 'havana_brown', label: 'Havana Brown' },
  { value: 'highlander', label: 'Highlander' },
  { value: 'himalayan', label: 'Himalayo' },
  { value: 'japanese_bobtail', label: 'Bobtail Japonés' },
  { value: 'javanese', label: 'Javanés' },
  { value: 'khao_manee', label: 'Khao Manee' },
  { value: 'korat', label: 'Korat' },
  { value: 'korean_bobtail', label: 'Bobtail Coreano' },
  { value: 'korn_ja', label: 'Korn Ja' },
  { value: 'kurilian_bobtail', label: 'Bobtail Kuriliano' },
  { value: 'laperm', label: 'LaPerm' },
  { value: 'lykoi', label: 'Lykoi' },
  { value: 'maine_coon', label: 'Maine Coon' },
  { value: 'manx', label: 'Manx' },
  { value: 'mekong_bobtail', label: 'Bobtail Mekong' },
  { value: 'minskin', label: 'Minskin' },
  { value: 'munchkin', label: 'Munchkin' },
  { value: 'nebelung', label: 'Nebelung' },
  { value: 'napoleon', label: 'Napoleón' },
  { value: 'norwegian_forest_cat', label: 'Bosque de Noruega' },
  { value: 'ocicat', label: 'Ocicat' },
  { value: 'ojos_azules', label: 'Ojos Azules' },
  { value: 'oregon_rex', label: 'Oregon Rex' },
  { value: 'oriental_bicolor', label: 'Oriental Bicolor' },
  { value: 'oriental_longhair', label: 'Oriental de Pelo Largo' },
  { value: 'oriental_shorthair', label: 'Oriental de Pelo Corto' },
  { value: 'persian', label: 'Persa' },
  { value: 'peterbald', label: 'Peterbald' },
  { value: 'pixie-bob', label: 'Pixie-bob' },
  { value: 'ragamuffin', label: 'Ragamuffin' },
  { value: 'ragdoll', label: 'Ragdoll' },
  { value: 'russian_blue', label: 'Azul Ruso' },
  { value: 'russian_white', label: 'Ruso Blanco' },
  { value: 'savannah', label: 'Savannah' },
  { value: 'scottish_fold', label: 'Scottish Fold' },
  { value: 'selkirk_rex', label: 'Selkirk Rex' },
  { value: 'serengeti', label: 'Serengeti' },
  { value: 'seychellois', label: 'Seychellois' },
  { value: 'siamese', label: 'Siamés' },
  { value: 'siberian', label: 'Siberiano' },
  { value: 'singapura', label: 'Singapura' },
  { value: 'snowshoe', label: 'Snowshoe' },
  { value: 'sokoke', label: 'Sokoke' },
  { value: 'somali', label: 'Somali' },
  { value: 'sphynx', label: 'Sphynx' },
  { value: 'suphalak', label: 'Suphalak' },
  { value: 'thai', label: 'Thai' },
  { value: 'tonkinese', label: 'Tonkinés' },
  { value: 'toyger', label: 'Toyger' },
  { value: 'turkish_angora', label: 'Angora Turco' },
  { value: 'turkish_van', label: 'Van Turco' },
  { value: 'ukrainian_levkoy', label: 'Levkoy Ucraniano' },
  { value: 'other', label: 'Otra raza específica' }
];
