export const dogBreedsOptions: any[] = [
    { value: 'Sin raza definida', label: 'Sin raza' },
  { value: 'Affenpinscher', label: 'Affenpinscher' },
  { value: 'Afgano', label: 'Afgano' },
  { value: 'Aidi', label: 'Aidi' },
  { value: 'Airedale Terrier', label: 'Airedale Terrier' },
  { value: 'Akbash', label: 'Akbash' },
  { value: 'Akita Inu', label: 'Akita Inu' },
  { value: 'Alano Español', label: 'Alano Español' },
  { value: 'Alaskan Klee Kai', label: 'Alaskan Klee Kai' },
  { value: 'Alaskan Malamute', label: 'Alaskan Malamute' },
  { value: 'Alpine Dachsbracke', label: 'Alpine Dachsbracke' },
  { value: 'Bulldog Americano', label: 'Bulldog Americano' },
  { value: 'Cocker Spaniel Americano', label: 'Cocker Spaniel Americano' },
  { value: 'Foxhound Americano', label: 'Foxhound Americano' },
  { value: 'Terrier Americano Sin Pelo', label: 'Terrier Americano Sin Pelo' },
  { value: 'American Staffordshire Terrier', label: 'American Staffordshire Terrier' },
  { value: 'Spaniel de Agua Americano', label: 'Spaniel de Agua Americano' },
  { value: 'Angol', label: 'Angol' },
  { value: 'Boyero de Appenzell', label: 'Boyero de Appenzell' },
  { value: 'Boyero Australiano', label: 'Boyero Australiano' },
  { value: 'Kelpie Australiano', label: 'Kelpie Australiano' },
  { value: 'Pastor Australiano', label: 'Pastor Australiano' },
  { value: 'Terrier Australiano', label: 'Terrier Australiano' },
  { value: 'Azawakh', label: 'Azawakh' },
  { value: 'Barbet', label: 'Barbet' },
  { value: 'Basenji', label: 'Basenji' },
  { value: 'Basset Artesiano Normando', label: 'Basset Artesiano Normando' },
  { value: 'Basset Azul de Gascuña', label: 'Basset Azul de Gascuña' },
  { value: 'Basset Leonado de Bretaña', label: 'Basset Leonado de Bretaña' },
  { value: 'Basset Hound', label: 'Basset Hound' },
  { value: 'Sabueso de Montaña de Baviera', label: 'Sabueso de Montaña de Baviera' },
  { value: 'Beagle', label: 'Beagle' },
  { value: 'Beagle-Harrier', label: 'Beagle-Harrier' },
  { value: 'Bearded Collie', label: 'Bearded Collie' },
  { value: 'Beauceron', label: 'Beauceron' },
  { value: 'Bedlington Terrier', label: 'Bedlington Terrier' },
  { value: 'Pastor Belga', label: 'Pastor Belga' },
  { value: 'Pastor de Bergamasco', label: 'Pastor de Bergamasco' },
  { value: 'Berger Picard', label: 'Berger Picard' },
  { value: 'Boyero de Berna', label: 'Boyero de Berna' },
  { value: 'Bichón Frisé', label: 'Bichón Frisé' },
  { value: 'Bichón Maltés', label: 'Bichón Maltés' },
  { value: 'Black and Tan Coonhound', label: 'Black and Tan Coonhound' },
  { value: 'Terrier Negro Ruso', label: 'Terrier Negro Ruso' },
  { value: 'Bloodhound', label: 'Bloodhound' },
  { value: 'Spaniel Azul de Picardía', label: 'Spaniel Azul de Picardía' },
  { value: 'Bluetick Coonhound', label: 'Bluetick Coonhound' },
  { value: 'Boerboel', label: 'Boerboel' },
  { value: 'Pastor de Bohemia', label: 'Pastor de Bohemia' },
  { value: 'Bolonés', label: 'Bolonés' },
  { value: 'Border Collie', label: 'Border Collie' },
  { value: 'Border Terrier', label: 'Border Terrier' },
  { value: 'Borzoi', label: 'Borzoi' },
  { value: 'Boston Terrier', label: 'Boston Terrier' },
  { value: 'Bouvier de Flandes', label: 'Bouvier de Flandes' },
  { value: 'Boxer', label: 'Boxer' },
  { value: 'Boykin Spaniel', label: 'Boykin Spaniel' },
  { value: 'Bracco Italiano', label: 'Bracco Italiano' },
  { value: 'Braco del Borbonesado', label: 'Braco del Borbonesado' },
  { value: 'Braco Francés', label: 'Braco Francés' },
  { value: 'Braco de Saint Germain', label: 'Braco de Saint Germain' },
  { value: 'Briard', label: 'Briard' },
  { value: 'Bretón Español', label: 'Bretón Español' },
  { value: 'Broholmer', label: 'Broholmer' },
  { value: 'Grifón de Bruselas', label: 'Grifón de Bruselas' },
  { value: 'Bull Terrier', label: 'Bull Terrier' },
  { value: 'Bulldog Inglés', label: 'Bulldog Inglés' },
  { value: 'Bullmastiff', label: 'Bullmastiff' },
  { value: 'Cairn Terrier', label: 'Cairn Terrier' },
  { value: 'Perro de Canaán', label: 'Perro de Canaán' },
  { value: 'Perro Esquimal Canadiense', label: 'Perro Esquimal Canadiense' },
  { value: 'Cane Corso', label: 'Cane Corso' },
  { value: 'Cardigan Welsh Corgi', label: 'Cardigan Welsh Corgi' },
  { value: 'Perro de Carolina', label: 'Perro de Carolina' },
  { value: 'Pastor Catalán', label: 'Pastor Catalán' },
  { value: 'Pastor del Cáucaso', label: 'Pastor del Cáucaso' },
  { value: 'Cavalier King Charles Spaniel', label: 'Cavalier King Charles Spaniel' },
  { value: 'Pastor de Asia Central', label: 'Pastor de Asia Central' },
  { value: 'Terrier Checo', label: 'Terrier Checo' },
  { value: 'Chesapeake Bay Retriever', label: 'Chesapeake Bay Retriever' },
    { value: 'Criollo', label: 'Criollo' },
  { value: 'Chihuahua', label: 'Chihuahua' },
  { value: 'Crestado Chino', label: 'Crestado Chino' },
  { value: 'Chinook', label: 'Chinook' },
  { value: 'Chow Chow', label: 'Chow Chow' },
  { value: 'Cirneco del Etna', label: 'Cirneco del Etna' },
  { value: 'Clumber Spaniel', label: 'Clumber Spaniel' },
  { value: 'Cocker Spaniel Inglés', label: 'Cocker Spaniel Inglés' },
  { value: 'Collie', label: 'Collie' },
  { value: 'Cotón de Tulear', label: 'Cotón de Tulear' },
  { value: 'Retriever de Pelo Rizado', label: 'Retriever de Pelo Rizado' },
  { value: 'Dachshund / Perro Salchicha', label: 'Dachshund / Perro Salchicha' },
  { value: 'Dálmata', label: 'Dálmata' },
  { value: 'Dandie Dinmont Terrier', label: 'Dandie Dinmont Terrier' },
  { value: 'Perro de Granja Danés-Sueco', label: 'Perro de Granja Danés-Sueco' },
  { value: 'Deerhound', label: 'Deerhound' },
  { value: 'Doberman Pinscher', label: 'Doberman Pinscher' },
  { value: 'Dogo Argentino', label: 'Dogo Argentino' },
  { value: 'Dogo de Burdeos', label: 'Dogo de Burdeos' },
  { value: 'Drentse Patrijshond', label: 'Drentse Patrijshond' },
  { value: 'Drever', label: 'Drever' },
  { value: 'Pastor Holandés', label: 'Pastor Holandés' },
  { value: 'Cocker Spaniel Inglés', label: 'Cocker Spaniel Inglés' },
  { value: 'Foxhound Inglés', label: 'Foxhound Inglés' },
  { value: 'Setter Inglés', label: 'Setter Inglés' },
  { value: 'Springer Spaniel Inglés', label: 'Springer Spaniel Inglés' },
  { value: 'Spaniel Toy Inglés', label: 'Spaniel Toy Inglés' },
  { value: 'Boyero de Entlebuch', label: 'Boyero de Entlebuch' },
  { value: 'Sabueso Estonio', label: 'Sabueso Estonio' },
  { value: 'Eurasier', label: 'Eurasier' },
  { value: 'Field Spaniel', label: 'Field Spaniel' },
  { value: 'Perro Finlandés de Laponia', label: 'Perro Finlandés de Laponia' },
  { value: 'Spitz Finlandés', label: 'Spitz Finlandés' },
  { value: 'Retriever de Pelo Liso', label: 'Retriever de Pelo Liso' },
  { value: 'Fox Terrier', label: 'Fox Terrier' },
  { value: 'Bulldog Francés', label: 'Bulldog Francés' },
  { value: 'Spaniel Francés', label: 'Spaniel Francés' },
  { value: 'Galgo Español', label: 'Galgo Español' },
  { value: 'Pointer Alemán de Pelo Largo', label: 'Pointer Alemán de Pelo Largo' },
  { value: 'Pinscher Alemán', label: 'Pinscher Alemán' },
  { value: 'Pastor Alemán', label: 'Pastor Alemán' },
  { value: 'Pointer Alemán de Pelo Corto', label: 'Pointer Alemán de Pelo Corto' },
  { value: 'Spitz Alemán', label: 'Spitz Alemán' },
  { value: 'Pointer Alemán de Pelo Duro', label: 'Pointer Alemán de Pelo Duro' },
  { value: 'Schnauzer Gigante', label: 'Schnauzer Gigante' },
  { value: 'Glen of Imaal Terrier', label: 'Glen of Imaal Terrier' },
  { value: 'Golden Retriever', label: 'Golden Retriever' },
  { value: 'Setter Gordon', label: 'Setter Gordon' },
  { value: 'Gran Basset Grifón Vendeano', label: 'Gran Basset Grifón Vendeano' },
  { value: 'Gran Danés', label: 'Gran Danés' },
  { value: 'Gran Pirineo', label: 'Gran Pirineo' },
  { value: 'Gran Boyero Suizo', label: 'Gran Boyero Suizo' },
  { value: 'Perro de Groenlandia', label: 'Perro de Groenlandia' },
  { value: 'Greyhound', label: 'Greyhound' },
  { value: 'Grifón de Bruselas', label: 'Grifón de Bruselas' },
  { value: 'Hamiltonstövare', label: 'Hamiltonstövare' },
  { value: 'Sabueso de Hannover', label: 'Sabueso de Hannover' },
  { value: 'Harrier', label: 'Harrier' },
  { value: 'Habanero', label: 'Habanero' },
  { value: 'Hokkaido', label: 'Hokkaido' },
  { value: 'Hovawart', label: 'Hovawart' },
  { value: 'Podenco Ibicenco', label: 'Podenco Ibicenco' },
  { value: 'Pastor Islandés', label: 'Pastor Islandés' },
  { value: 'Setter Irlandés Rojo y Blanco', label: 'Setter Irlandés Rojo y Blanco' },
  { value: 'Setter Irlandés', label: 'Setter Irlandés' },
  { value: 'Terrier Irlandés', label: 'Terrier Irlandés' },
  { value: 'Spaniel de Agua Irlandés', label: 'Spaniel de Agua Irlandés' },
  { value: 'Wolfhound Irlandés', label: 'Wolfhound Irlandés' },
  { value: 'Galguito Italiano', label: 'Galguito Italiano' },
  { value: 'Spaniel Japonés', label: 'Spaniel Japonés' },
  { value: 'Spitz Japonés', label: 'Spitz Japonés' },
  { value: 'Jindo Coreano', label: 'Jindo Coreano' },
  { value: 'Kai Ken', label: 'Kai Ken' },
  { value: 'Kangal', label: 'Kangal' },
  { value: 'Perro de Osos de Carelia', label: 'Perro de Osos de Carelia' },
  { value: 'Keeshond', label: 'Keeshond' },
  { value: 'Terrier Kerry Blue', label: 'Terrier Kerry Blue' },
  { value: 'King Charles Spaniel', label: 'King Charles Spaniel' },
  { value: 'Kishu', label: 'Kishu' },
  { value: 'Komondor', label: 'Komondor' },
  { value: 'Kuvasz', label: 'Kuvasz' },
  { value: 'Labrador Retriever', label: 'Labrador Retriever' },
  { value: 'Lagotto Romagnolo', label: 'Lagotto Romagnolo' },
  { value: 'Lakeland Terrier', label: 'Lakeland Terrier' },
  { value: 'Lancashire Heeler', label: 'Lancashire Heeler' },
  { value: 'Leonberger', label: 'Leonberger' },
  { value: 'Lhasa Apso', label: 'Lhasa Apso' },
  { value: 'Lowchen', label: 'Lowchen' },
  { value: 'Maltés', label: 'Maltés' },
  { value: 'Manchester Terrier', label: 'Manchester Terrier' },
  { value: 'Mastín Inglés', label: 'Mastín Inglés' },
  { value: 'Mestizo', label: 'Mestizo' },
  { value: 'Pastor Americano Miniatura', label: 'Pastor Americano Miniatura' },
  { value: 'Bull Terrier Miniatura', label: 'Bull Terrier Miniatura' },
  { value: 'Pinscher Miniatura', label: 'Pinscher Miniatura' },
  { value: 'Schnauzer Miniatura', label: 'Schnauzer Miniatura' },
  { value: 'Mudi', label: 'Mudi' },
  { value: 'Mastín Napolitano', label: 'Mastín Napolitano' },
  { value: 'Perro Cantor de Nueva Guinea', label: 'Perro Cantor de Nueva Guinea' },
  { value: 'Terranova', label: 'Terranova' },
  { value: 'Norfolk Terrier', label: 'Norfolk Terrier' },
  { value: 'Buhund Noruego', label: 'Buhund Noruego' },
  { value: 'Elkhound Noruego', label: 'Elkhound Noruego' },
  { value: 'Lundehund Noruego', label: 'Lundehund Noruego' },
  { value: 'Norwich Terrier', label: 'Norwich Terrier' },
  { value: 'Retriever de Nueva Escocia', label: 'Retriever de Nueva Escocia' },
  { value: 'Viejo Pastor Inglés', label: 'Viejo Pastor Inglés' },
  { value: 'Otterhound', label: 'Otterhound' },
  { value: 'Papillón', label: 'Papillón' },
  { value: 'Parson Russell Terrier', label: 'Parson Russell Terrier' },
  { value: 'Pekinés', label: 'Pekinés' },
  { value: 'Pembroke Welsh Corgi', label: 'Pembroke Welsh Corgi' },
  { value: 'Presa Canario', label: 'Presa Canario' },
  { value: 'Perro Sin Pelo del Perú', label: 'Perro Sin Pelo del Perú' },
  { value: 'Pequeño Basset Grifón Vendeano', label: 'Pequeño Basset Grifón Vendeano' },
  { value: 'Perro del Faraón', label: 'Perro del Faraón' },
  { value: 'Plott Hound', label: 'Plott Hound' },
  { value: 'Pointer Inglés', label: 'Pointer Inglés' },
  { value: 'Pastor de Valée', label: 'Pastor de Valée' },
  { value: 'Pomerania', label: 'Pomerania' },
  { value: 'Caniche / Poodle', label: 'Caniche / Poodle' },
  { value: 'Porcelaine', label: 'Porcelaine' },
  { value: 'Podengo Portugués', label: 'Podengo Portugués' },
  { value: 'Perro de Muestra Portugués', label: 'Perro de Muestra Portugués' },
  { value: 'Perro de Agua Portugués', label: 'Perro de Agua Portugués' },
  { value: 'Pudelpointer', label: 'Pudelpointer' },
  { value: 'Pug / Carlino', label: 'Pug / Carlino' },
  { value: 'Puli', label: 'Puli' },
  { value: 'Pumi', label: 'Pumi' },
  { value: 'Mastín del Pirineo', label: 'Mastín del Pirineo' },
  { value: 'Pastor de los Pirineos', label: 'Pastor de los Pirineos' },
  { value: 'Rafeiro do Alentejo', label: 'Rafeiro do Alentejo' },
  { value: 'Redbone Coonhound', label: 'Redbone Coonhound' },
  { value: 'Ridgeback de Rodesia', label: 'Ridgeback de Rodesia' },
  { value: 'Pastor Rumanio Miorítico', label: 'Pastor Rumanio Miorítico' },
  { value: 'Rottweiler', label: 'Rottweiler' },
  { value: 'Terrier Negro Ruso', label: 'Terrier Negro Ruso' },
  { value: 'Toy Ruso', label: 'Toy Ruso' },
  { value: 'Bolonka Ruso', label: 'Bolonka Ruso' },
  { value: 'San Bernardo', label: 'San Bernardo' },
  { value: 'Saluki', label: 'Saluki' },
  { value: 'Samoyedo', label: 'Samoyedo' },
  { value: 'Schapendoes', label: 'Schapendoes' },
  { value: 'Schipperke', label: 'Schipperke' },
  { value: 'Deerhound Escocés', label: 'Deerhound Escocés' },
  { value: 'Terrier Escocés', label: 'Terrier Escocés' },
  { value: 'Sealyham Terrier', label: 'Sealyham Terrier' },
  { value: 'Segugio Italiano', label: 'Segugio Italiano' },
  { value: 'Shar Pei', label: 'Shar Pei' },
  { value: 'Shetland Sheepdog', label: 'Shetland Sheepdog' },
  { value: 'Shiba Inu', label: 'Shiba Inu' },
  { value: 'Shih Tzu', label: 'Shih Tzu' },
  { value: 'Shikoku', label: 'Shikoku' },
  { value: 'Husky Siberiano', label: 'Husky Siberiano' },
  { value: 'Terrier Sedoso Australiano', label: 'Terrier Sedoso Australiano' },
  { value: 'Skye Terrier', label: 'Skye Terrier' },
  { value: 'Sloughi', label: 'Sloughi' },
  { value: 'Pointer de Pelo Duro Eslovaco', label: 'Pointer de Pelo Duro Eslovaco' },
  { value: 'Slovensky Cuvac', label: 'Slovensky Cuvac' },
  { value: 'Slovensky Kopov', label: 'Slovensky Kopov' },
  { value: 'Pequeño Munsterlander', label: 'Pequeño Munsterlander' },
  { value: 'Fox Terrier de Pelo Liso', label: 'Fox Terrier de Pelo Liso' },
  { value: 'Terrier de Trigo de Pelo Suave', label: 'Terrier de Trigo de Pelo Suave' },
  { value: 'Mastín Español', label: 'Mastín Español' },
  { value: 'Perro de Agua Español', label: 'Perro de Agua Español' },
  { value: 'Spinone Italiano', label: 'Spinone Italiano' },
  { value: 'Stabyhoun', label: 'Stabyhoun' },
  { value: 'Staffordshire Bull Terrier', label: 'Staffordshire Bull Terrier' },
  { value: 'Schnauzer Estándar', label: 'Schnauzer Estándar' },
  { value: 'Sussex Spaniel', label: 'Sussex Spaniel' },
  { value: 'Perro Sueco de Laponia', label: 'Perro Sueco de Laponia' },
  { value: 'Vallhund Sueco', label: 'Vallhund Sueco' },
  { value: 'Perro de Taiwán', label: 'Perro de Taiwán' },
  { value: 'Terrier Teddy Roosevelt', label: 'Terrier Teddy Roosevelt' },
  { value: 'Mastín Tibetano', label: 'Mastín Tibetano' },
  { value: 'Spaniel Tibetano', label: 'Spaniel Tibetano' },
  { value: 'Terrier Tibetano', label: 'Terrier Tibetano' },
  { value: 'Tornjak', label: 'Tornjak' },
  { value: 'Tosa Inu', label: 'Tosa Inu' },
  { value: 'Toy Fox Terrier', label: 'Toy Fox Terrier' },
  { value: 'Sabueso de Transilvania', label: 'Sabueso de Transilvania' },
  { value: 'Treeing Tennessee Brindle', label: 'Treeing Tennessee Brindle' },
  { value: 'Treeing Walker Coonhound', label: 'Treeing Walker Coonhound' },
  { value: 'Volpino Italiano', label: 'Volpino Italiano' },
  { value: 'Weimaraner', label: 'Weimaraner' },
  { value: 'Springer Spaniel Galés', label: 'Springer Spaniel Galés' },
  { value: 'Terrier Galés', label: 'Terrier Galés' },
  { value: 'West Highland White Terrier', label: 'West Highland White Terrier' },
  { value: 'Wetterhoun', label: 'Wetterhoun' },
  { value: 'Whippet', label: 'Whippet' },
  { value: 'Fox Terrier de Pelo Duro', label: 'Fox Terrier de Pelo Duro' },
  { value: 'Grifón de Muestra de Pelo Duro', label: 'Grifón de Muestra de Pelo Duro' },
  { value: 'Vizsla de Pelo Duro', label: 'Vizsla de Pelo Duro' },
  { value: 'Xoloitzcuintli', label: 'Xoloitzcuintli' },
  { value: 'Laika de Yakutia', label: 'Laika de Yakutia' },
  { value: 'Yorkshire Terrier', label: 'Yorkshire Terrier' },
  { value: 'Otra raza específica', label: 'Otra raza específica' }
];
